package com.droidkaigi.quiz.core.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

object QuizColors {
    fun light() = lightColorScheme(
        primary = QuizTokens.primary,
        onPrimary = QuizTokens.onPrimary,
        primaryContainer = QuizTokens.primaryContainer,
        onPrimaryContainer = QuizTokens.onPrimaryContainer,
        secondary = QuizTokens.secondary,
        onSecondary = QuizTokens.onSecondary,
        secondaryContainer = QuizTokens.secondaryContainer,
        onSecondaryContainer = QuizTokens.onSecondaryContainer,
        surface = QuizTokens.surface,
        onSurface = QuizTokens.onSurface,
        onSurfaceVariant = QuizTokens.onSurfaceVariant,
        background = QuizTokens.gradientStartLight,
        onBackground = QuizTokens.onSurface,
        surfaceContainer = QuizTokens.surface,
        surfaceContainerLow = QuizTokens.surface,
        surfaceContainerHigh = QuizTokens.surfaceElevated,
        surfaceContainerHighest = QuizTokens.surfaceElevated,
        outline = QuizTokens.outline,
        error = QuizTokens.incorrect,
    )

    fun dark() = darkColorScheme(
        primary = QuizTokens.primaryDark,
        onPrimary = QuizTokens.onPrimaryDark,
        primaryContainer = QuizTokens.primaryContainerDark,
        onPrimaryContainer = QuizTokens.onPrimaryContainerDark,
        secondary = QuizTokens.secondaryDark,
        onSecondary = QuizTokens.onSecondaryDark,
        secondaryContainer = QuizTokens.secondaryContainerDark,
        onSecondaryContainer = QuizTokens.onSecondaryContainerDark,
        surface = QuizTokens.surfaceDark,
        onSurface = QuizTokens.onSurfaceDark,
        onSurfaceVariant = QuizTokens.onSurfaceVariantDark,
        background = QuizTokens.gradientStartDark,
        onBackground = QuizTokens.onSurfaceDark,
        surfaceContainer = QuizTokens.surfaceDark,
        surfaceContainerLow = QuizTokens.surfaceDark,
        surfaceContainerHigh = QuizTokens.secondaryContainerDark,
        surfaceContainerHighest = QuizTokens.secondaryContainerDark,
        outline = QuizTokens.outlineDark,
        error = QuizTokens.incorrect,
    )

    /** Dark-only scheme for the staff console; venue rooms are dim and shifts are long. */
    fun staffDark() = darkColorScheme(
        primary = QuizTokens.staffPrimary,
        onPrimary = QuizTokens.staffOnPrimary,
        primaryContainer = QuizTokens.staffPrimaryContainer,
        onPrimaryContainer = QuizTokens.staffOnPrimaryContainer,
        inversePrimary = QuizTokens.staffInversePrimary,
        secondary = QuizTokens.staffSecondary,
        onSecondary = QuizTokens.staffOnSecondary,
        secondaryContainer = QuizTokens.staffSecondaryContainer,
        onSecondaryContainer = QuizTokens.staffOnSecondaryContainer,
        tertiary = QuizTokens.staffTertiary,
        onTertiary = QuizTokens.staffOnTertiary,
        tertiaryContainer = QuizTokens.staffTertiaryContainer,
        onTertiaryContainer = QuizTokens.staffOnTertiaryContainer,
        background = QuizTokens.staffSurface,
        onBackground = QuizTokens.staffOnSurface,
        surface = QuizTokens.staffSurface,
        onSurface = QuizTokens.staffOnSurface,
        surfaceVariant = QuizTokens.staffSurfaceVariant,
        onSurfaceVariant = QuizTokens.staffOnSurfaceVariant,
        surfaceBright = QuizTokens.staffSurfaceBright,
        surfaceDim = QuizTokens.staffSurface,
        surfaceContainerLowest = QuizTokens.staffSurfaceContainerLowest,
        surfaceContainerLow = QuizTokens.staffSurfaceContainerLow,
        surfaceContainer = QuizTokens.staffSurfaceContainer,
        surfaceContainerHigh = QuizTokens.staffSurfaceContainerHigh,
        surfaceContainerHighest = QuizTokens.staffSurfaceContainerHighest,
        inverseSurface = QuizTokens.staffInverseSurface,
        inverseOnSurface = QuizTokens.staffInverseOnSurface,
        outline = QuizTokens.staffOutline,
        outlineVariant = QuizTokens.staffOutlineVariant,
        error = QuizTokens.staffError,
        onError = QuizTokens.staffOnError,
        errorContainer = QuizTokens.staffErrorContainer,
        onErrorContainer = QuizTokens.staffOnErrorContainer,
    )
}
