import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.androidKmpLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.metro)
}

val quizRuntime = rootProject.extra["quizRuntime"] as String
val usesProdBackend = rootProject.extra["usesProdBackend"] as Boolean
val useFirebaseEmulator = rootProject.extra["useFirebaseEmulator"] as Boolean
check(quizRuntime in setOf("fake", "prod", "local")) {
    "quiz.runtime must be 'fake', 'prod', or 'local' (was '$quizRuntime')."
}
val quizRuntimeSourceSetDir = if (usesProdBackend) "prodMain" else "fakeMain"

kotlin {
    android {
        namespace = "com.droidkaigi.quiz.core.data"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
        androidResources {
            enable = true
        }
        withHostTest {}
    }
    jvm {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
    }

    sourceSets {
        commonMain {
            kotlin.srcDir("src/$quizRuntimeSourceSetDir/kotlin")
        }
        commonMain.dependencies {
            implementation(project(":core:domain"))
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.compose.runtime)
            implementation(libs.compose.components.resources)
            implementation(libs.metro.runtime)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }
        jvmTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }
    }
    if (usesProdBackend) {
        val prodGitLiveDir = "src/prodGitLive/kotlin"
        sourceSets.named("androidMain").configure {
            kotlin.srcDir("src/prodAndroid/kotlin")
            kotlin.srcDir(prodGitLiveDir)
            dependencies {
                implementation(libs.firebase.common.lib)
                implementation(libs.firebase.auth.ktx)
                implementation(libs.firebase.firestore.ktx)
                implementation(libs.firebase.app)
                implementation(libs.firebase.auth)
                implementation(libs.firebase.firestore)
            }
        }
        sourceSets.named("jvmMain").configure {
            kotlin.srcDir("src/prodJvm/kotlin")
            kotlin.srcDir(prodGitLiveDir)
            dependencies {
                implementation(libs.firebase.app)
                implementation(libs.firebase.auth)
                implementation(libs.firebase.firestore)
                implementation(libs.firebase.java.sdk)
            }
        }
        sourceSets.named("wasmJsMain").configure {
            kotlin.srcDir("src/prodWasm/kotlin")
        }
    }
    if (quizRuntime != "fake") {
        sourceSets.named("jvmTest").configure {
            kotlin.exclude("**/FakeRankingRepositoryTest.kt")
        }
    }
}

if (usesProdBackend) {
    val generatedDir = layout.buildDirectory.dir("generated/quizRuntime/kotlin")
    val emulatorEnabled = useFirebaseEmulator
    val runtimeLabel = quizRuntime
    val quizRuntimeFlagsSource =
        """
        |package com.droidkaigi.quiz.core.data.firestore
        |
        |/** Generated by Gradle from quiz.runtime ($runtimeLabel). Do not edit. */
        |internal object QuizRuntimeFlags {
        |    const val USE_FIREBASE_EMULATOR: Boolean = $emulatorEnabled
        |}
        """.trimMargin()
    val generateQuizRuntimeFlags =
        tasks.register("generateQuizRuntimeFlags") {
            // quiz.runtime 切替時に必ず再生成する（inputs 無しだと local→prod で UP-TO-DATE のまま残る）
            inputs.property("quizRuntime", runtimeLabel)
            inputs.property("useFirebaseEmulator", emulatorEnabled)
            outputs.dir(generatedDir)
            doLast {
                val packageDir =
                    generatedDir.get().asFile.resolve("com/droidkaigi/quiz/core/data/firestore")
                packageDir.mkdirs()
                packageDir.resolve("QuizRuntimeFlags.kt").writeText(quizRuntimeFlagsSource)
            }
        }
    kotlin.sourceSets.named("commonMain").configure {
        kotlin.srcDir(generatedDir)
    }
    tasks.withType<KotlinCompile>().configureEach {
        dependsOn(generateQuizRuntimeFlags)
    }
}

compose.resources {
    publicResClass = true
    packageOfResClass = "com.droidkaigi.quiz.core.data.generated.resources"
}
